### ISSUE TITLE
Sign up option for new members, volunteers, sponsors, partners

### ISSUE THREAD

**Issue by domsbytes** [wwcodecolorado/career-returnship-website#25]

**Comment by OlliesWorld** [comment]
Is this basically another contact form with options to pick what type the person is?

**Comment by domsbytes** [comment]
Hey good question @OlliesWorld ! I would ask @Rafna , but I think I meant to create this issue to finish the "Become a Member" buttons to actually connect the website to a google form Rafna uses to have new people actually sign up for the program. I see that right now the button takes to the contact form. But I suggest maybe adding another page explaining who this program is for and who should join and why should join etc., sort of the stuff Rafna always touches on when she introduces new members and the another final "become a member" button inside of it. Maybe with this site, she can just open it and use it as a visual aid when talking about joining the group. :)

**Comment by domsbytes** [comment]
You could make a really fancy form, i,e, recreate the google form :) form scratch which could be fun? google form is just nice because it could fill out a spreadsheet for Rafna if she wanted to look at all the responses in one place. Another advanced issue idea would be to hook a database to store and parse all the data.

**Comment by OlliesWorld** [comment]
Thanks @domsbytes for some great ideas. I really like using TypeForm but they do not have a free version. We could go with JotForm or Tripetto. I have not used Tripetto, but it looks like it might be a neat app. I will explore and share what I come up with. Of course Webhooks will be involved as they are so useful!
