### ISSUE TITLE
Create Information Architecture Map

### ISSUE THREAD

**Issue by cssteffen** [wwcodecolorado/career-returnship-website#6]
Create Map of Informational Architect to guide website user flow and lay-out

**Comment by cssteffen** [comment]
[SiteMap-CAREER RETURNSHIP.pdf](https://github.com/wwcodecolorado/career-returnship-website/files/4458919/SiteMap-CAREER.RETURNSHIP.pdf)

**Comment by cssteffen** [comment]
<img width="983" alt="Screen Shot 2020-04-09 at 5 01 13 PM" src="https://user-images.githubusercontent.com/30050423/78947838-c4d7c180-7a83-11ea-9ed5-67ef66366f19.png">

**Comment by Rafna** [comment]
Message in contact should be sending to email as we are trying to connect with employers who are hiring. Footer nav need some research on what can we include, We'll update later but keep those as an optional navs.
