### ISSUE TITLE
Create Brand Identity

### ISSUE THREAD

**Issue by cssteffen** [wwcodecolorado/career-returnship-website#8]
Design Logo
Define Color Scheme & Font usage
Create Favicon Design

**Comment by cssteffen** [comment]
<img width="378" alt="Screen Shot 2020-04-09 at 5 31 47 PM" src="https://user-images.githubusercontent.com/30050423/78949176-14b88780-7a88-11ea-9d0a-aa06b3204310.png">

**Comment by cssteffen** [comment]
<img width="232" alt="Screen Shot 2020-04-09 at 5 33 46 PM" src="https://user-images.githubusercontent.com/30050423/78949275-55180580-7a88-11ea-9f4e-daaca1c398c0.png">

**Comment by cssteffen** [comment]
<img width="173" alt="Screen Shot 2020-04-09 at 5 35 55 PM" src="https://user-images.githubusercontent.com/30050423/78949390-a1fbdc00-7a88-11ea-94c1-6b8e94de2bda.png">

**Comment by Rafna** [comment]
Design is completed
